pub mod accessibility;
pub mod capture;
pub mod clipboard;
pub mod desktop;
pub mod desktop_state;
pub mod display;
pub mod glow;
pub mod glow_state;
pub mod glow_watch;
mod hyprland;
pub mod idle;
pub mod image_copy;
pub mod input;
pub mod kwin_screenshot;
pub mod pipewire_source;
pub mod readiness;
pub mod session;
