[package]
name = "pcbridge-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
test-harness = []

[dependencies]
async-io.workspace = true
futures-lite.workspace = true
pcbridge-core = { path = "../pcbridge-core" }
serde.workspace = true
serde_json.workspace = true
zbus.workspace = true

[dev-dependencies]
serde_json.workspace = true
