"""Provider protocols at the Python/native desktop boundary.

The protocols describe only operations used by the current Python callers.
Later native providers can implement the same surface without making MCP tools
own backend processes or device handles.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Hashable, Protocol, Sequence, runtime_checkable

from .capabilities import Capability
from .safety import ActivityObservation, ScreenLockObservation


@runtime_checkable
class CaptureProvider(Protocol):
    def capability_token(self) -> Hashable: ...

    def probe_capabilities(self) -> dict[str, Capability]: ...

    def start(self, *, cursor: bool | None = None) -> dict: ...

    def close(self) -> None: ...

    def is_open(self) -> bool: ...

    def available(self) -> tuple[bool, str]: ...

    def backend_name(self) -> str: ...

    def capture(
        self,
        spec: int | str,
        *,
        out_dir: Path,
        scale_long_edge: int,
        include_pointer: bool,
    ) -> list[Any]: ...

    def list_monitors(self) -> list[Any]: ...

    def topology_id(self) -> str: ...


    def describe_monitors(self) -> str: ...

    def find_monitor(self, x: int, y: int) -> Any | None: ...

    def to_global(
        self,
        x: int,
        y: int,
        *,
        monitor: int | str | None = None,
        shot: str | None = None,
        dirs: Sequence[Path] | None = None,
        guard_age: float = 0.0,
    ) -> tuple[int, int]: ...

    def load_shot(self, shot_id: str, dirs: Sequence[Path]) -> Any: ...

    def save_meta(self, shot: Any, out_dir: Path | None = None) -> Path | None: ...

    def oversize_note(self, shot: Any) -> str: ...

    def kill_helpers(self) -> int: ...


@runtime_checkable
class InputProvider(Protocol):
    def capability_token(self) -> Hashable: ...

    def probe_capabilities(self) -> dict[str, Capability]: ...

    def available(self) -> tuple[bool, str]: ...

    def ensure(self, keyboard: bool = False, pointer: bool = False) -> float: ...

    def close(self) -> None: ...

    def held(self) -> list[str]: ...

    def release_all(self) -> list[str]: ...

    def take_auto_released(self) -> list[str]: ...

    @property
    def position(self) -> tuple[int, int] | None: ...

    def move(self, x: int, y: int, smooth: bool | None = None) -> tuple[int, int]: ...

    def click(self, button: str = "left", count: int = 1) -> None: ...

    def drag(
        self,
        x: int,
        y: int,
        to_x: int,
        to_y: int,
        button: str = "left",
    ) -> None: ...

    def scroll(self, amount: int, horizontal: bool = False) -> None: ...

    def mouse_down(self, button: str = "left") -> None: ...

    def mouse_up(self, button: str = "left") -> None: ...

    def key(self, combo: str) -> None: ...

    def key_down(self, combo: str) -> None: ...

    def key_up(self, combo: str) -> None: ...

    def type_text(self, text: str, raw: bool, restore_clipboard: bool) -> str: ...


@runtime_checkable
class AccessibilityProvider(Protocol):
    def capability_token(self) -> Hashable: ...

    def probe_capabilities(self) -> dict[str, Capability]: ...

    def available(self) -> tuple[bool, str]: ...

    def dump(
        self,
        target: str = "focused",
        interactive_only: bool = True,
        max_nodes: int = 400,
    ) -> Any: ...

    def focused_window(self) -> tuple[str, str]: ...

    def windows(self) -> list[Any]: ...

    def click(self, node_id: str, action: str = "click") -> dict: ...

    def set_text(self, node_id: str, text: str) -> dict: ...

    def describe_dump(self, dump: Any) -> str: ...

    def describe_windows(self, windows: list[Any]) -> str: ...


@runtime_checkable
class GrantProvider(Protocol):
    spec: Any

    def check(self, tool: str, *, write: bool, force: bool = False) -> Any: ...

    def audit(self, event: str, **fields: Any) -> None: ...

    def unlock(self, minutes: int, reason: str = "") -> str: ...

    def lock(self) -> str: ...

    def touch(self, token: Any | None = None) -> bool: ...

    def current_token(self) -> Any | None: ...

    def last_token(self) -> Any | None: ...

    @property
    def revoke_epoch(self) -> int: ...

    def is_unlocked(self) -> bool: ...

    def remaining_seconds(self) -> float: ...

    def hard_remaining_seconds(self) -> float: ...

    def status_line(self) -> str: ...


@runtime_checkable
class DesktopStateProvider(Protocol):
    def screen_lock(self) -> ScreenLockObservation: ...

    def user_activity(self) -> ActivityObservation: ...


__all__ = [
    "AccessibilityProvider",
    "CaptureProvider",
    "DesktopStateProvider",
    "GrantProvider",
    "InputProvider",
]
